# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration for EatLock Project
# 暴飲暴食抑制アプリのためのコードレビュー設定

# 基本レビュー設定
reviews:
  # 自動レビューの設定（オブジェクト形式）
  auto_review:
    enabled: true
    # 自動レビューを実行する対象ブランチパターン
    base_branches: ["feature/*", "bugfix/*", "hotfix/*"]
    # レビューをトリガーする条件
    on_push: true
    on_pull_request: true
    # 除外するファイル
    exclude:
      - "**/xcuserdata/**"
      - "**/DerivedData/**"
      - "**/Pods/**"
      - "**/.build/**"
      - "**/Preview Content/**"
      - "**/*.xcassets/**"
      - "**/fastlane/**"

  # レビューステータスの表示
  review_status: true

  # レビューの詳細度
  high_level_summary: true

# パス設定
path_instructions:
  # Swift/iOS固有の設定
  - path: "**/*.swift"
    instructions: |
      - SwiftUIのベストプラクティスに従っているかチェック
      - メモリ管理（ARC）の問題がないかチェック
      - プロトコル準拠が適切かチェック
      - 命名規則がSwiftのコンベンションに従っているかチェック
      - オプショナルの適切な使用をチェック
      - プライバシーとセキュリティの観点からコードをレビュー

  - path: "**/*.md"
    instructions: |
      - ドキュメントの構造と内容の明確さをチェック
      - 日本語の文章が適切かチェック
      - コード例が正確かチェック

  - path: "**/ContentView.swift"
    instructions: |
      - UIレイアウトの実装が要求仕様に合っているかチェック
      - ユーザーエクスペリエンスの観点から評価
      - アクセシビリティの対応状況をチェック

  - path: "**/ActionLog.swift"
    instructions: |
      - データモデルの設計が適切かチェック
      - データの暗号化処理が正しく実装されているかチェック
      - パフォーマンスの観点から評価

# 言語設定
language: "ja"

# 自動修正の設定
auto_fix:
  # 自動修正を有効にする
  enabled: true
  # 安全な修正のみ実行
  safe_only: true